development:
  sessions:
    default:
      database: nsumint_development
      hosts:
        - localhost:27017
      options:
  options:
test:
  sessions:
    default:
      database: nsumint_test
      hosts:
        - localhost:27017
      options:
        read: primary
        max_retries: 1
        retry_interval: 0
production:
  sessions:
    default:
      database: nsumint_production
      hosts:
        - localhost:27017
