Faculty.find_or_create_by(name: 'ГГФ')
Faculty.find_or_create_by(name: 'ГФ')
Faculty.find_or_create_by(name: 'МедФ')
Faculty.find_or_create_by(name: 'ММФ')
Faculty.find_or_create_by(name: 'ФЖ')
Faculty.find_or_create_by(name: 'ФЕН')
Faculty.find_or_create_by(name: 'ФИТ')
Faculty.find_or_create_by(name: 'ФИЯ')
Faculty.find_or_create_by(name: 'ФП')
Faculty.find_or_create_by(name: 'ФФ')
Faculty.find_or_create_by(name: 'ФилФ')
Faculty.find_or_create_by(name: 'ЭФ')
Faculty.find_or_create_by(name: 'ЮФ')
Faculty.find_or_create_by(name: 'Другой ВУЗ')

